### ISSUE TITLE
cannot connect to database with password that contains an ü (u-umlaut)

### ISSUE THREAD

**Issue by sma** [mongo-dart/sasl_scram#1]
I think this library cannot correctly encode passwords that contain unicode letters. See my discussion here: https://github.com/isoos/postgresql-dart/issues/38.

**Comment by giorgiofran** [comment]
You are right. There are some problems with unicode characters.
I guess that I got the problem, and I will provide a fix on github in the next days.
Could you please help me testing when available?

**Comment by giorgiofran** [comment]
I have uploaded the fix in the github repo only at present. Could you please do some additional testing? Thanks in advance

**Comment by sma** [comment]
I'm sorry for the silence. I checked and the version from master works. Thanks.

**Comment by giorgiofran** [comment]
Thanks, I have published it.
